lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 86400 #Le temps est volontairement long, pour ne pas avoir à refresh le token trop régulièrement durant les tests
    user_identity_field: email
